# Generated by Django 3.2.7 on 2022-04-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MClothing', '0002_auto_20220401_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
