# Generated by Django 3.2.7 on 2022-04-02 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MClothing', '0006_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_rating', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MClothing.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MClothing.customer')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
