# Generated by Django 3.2.7 on 2022-05-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEhub', '0002_auto_20220518_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoptions',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
